<?php

define('AUDIT_ADD_BLACKLIST_ITEM', 'ADD_BLACKLIST_ITEM');
define('AUDIT_ADD_BOOKING', 'ADD_BOOKING');
define('AUDIT_ADD_C_SCHEDULE', 'ADD_CLEANER_SCHEDULE');
define('AUDIT_ADD_MENDING_ITEM', 'ADD_MENDING_ITEM');
define('AUDIT_ADD_SCHEDULE', 'ADD_RECEPTIONIST_SCHEDULE');
define('AUDIT_ADD_SHOPPING_ITEM', 'ADD_SHOPPING_ITEM');
define('AUDIT_BCR_SENT', 'BCR_SENT');
define('AUDIT_CANCEL_BOOKING', 'CANCEL_BOOKING');
define('AUDIT_CHANGE_BOOKING_DATE', 'CHANGE_BOOKING_DATE');
define('AUDIT_CHECKIN_BOOKING', 'CHECKIN_BOOKING');
define('AUDIT_CHECKOUT_BOOKING', 'CHECKOUT_BOOKING');
define('AUDIT_CONFIRM_BOOKING', 'CONFIRM_BOOKING');
define('AUDIT_CREATE_BOOKING', 'CREATE_BOOKING');
define('AUDIT_DELETE_BLACKLIST_ITEM', 'DELETE_BLACKLIST_ITEM');
define('AUDIT_DELETE_BOOKING', 'DELETE_BOOKING');
define('AUDIT_DELETE_MENDING_ITEM', 'DELETE_MENDING_ITEM');
define('AUDIT_DELETE_SHOPPING_ITEM', 'DELETE_SHOPPING_ITEM');
define('AUDIT_EDIT_BOOKING', 'EDIT_BOOKING');
define('AUDIT_GUEST_TRANSFER_ADDED', 'GUEST_TRANSFER_ADDED');
define('AUDIT_GUEST_TRANSFER_DELETED', 'GUEST_TRANSFER_DELETED');
define('AUDIT_LOCK_ROOMS', 'LOCK_ROOMS');
define('AUDIT_MAINTENANCE_BOOKING', 'MAINTENANCE_BOOKING');
define('AUDIT_NOTPAID_BOOKING', 'NOTPAID_BOOKING');
define('AUDIT_PAID_BOOKING', 'PAID_BOOKING');
define('AUDIT_PAYMENT_ADDED', 'PAYMENT_ADDED');
define('AUDIT_REMOVE_C_SCHEDULE', 'REMOVE_CLEANER_SCHEDULE');
define('AUDIT_REMOVE_GUEST_DATA', 'REMOVE_GUEST_DATA');
define('AUDIT_REMOVE_SCHEDULE', 'REMOVE_RECEPTIONIST_SCHEDULE');
define('AUDIT_SAVE_CASH_OUT', 'SAVE_CASHOUT');
define('AUDIT_SAVE_CASH_IN', 'SAVE_CASHIN');
define('AUDIT_SAVE_DAY_CLOSE', 'DAY_CLOSE');
define('AUDIT_SAVE_EXTRA_BEDS', 'SAVE_EXTRA_BEDS');
define('AUDIT_SAVE_GUEST_DATA', 'SAVE_GUEST_DATA');
define('AUDIT_SAVE_MENDING_ITEM', 'ADD_MENDING_ITEM');
define('AUDIT_SAVE_SHOPPING_ITEM', 'ADD_SHOPPING_ITEM');
define('AUDIT_SERVICE_CHARGE_ADDED', 'SERVICE_CHARGE_ADDED');
define('AUDIT_SET_BCR_SENT', 'SET_BCR_SENT');
define('AUDIT_STORNO_ITEM', 'STORNO_ITEM');
define('AUDIT_UNCANCEL_BOOKING', 'UNCANCEL_BOOKING');
define('AUDIT_UNCONFIRM_BOOKING', 'UNCONFIRM_BOOKING');

function audit($type, $data, $bookingId, $bookingDescriptionId, $link) {
	$login = $_SESSION['login_user'];
	$time = date('Y-m-d H:i:s');
	if(is_null($bookingId)) {
		$bookingId = 'NULL';
	}
	$sql = "INSERT INTO audit (time_of_event, type, booking_id, booking_description_id, data, login) VALUES ('$time', '$type', '$bookingId', '$bookingDescriptionId', '" . mysql_real_escape_string(print_r($data, true), $link) . "', '$login')";
	if(!mysql_query($sql, $link)) {
		trigger_error("Cannot save audit log: " . mysql_error($link) . " (SQL: $sql)");
	}
}

?>
